"""
Django settings for geodjango project.

Generated by 'django-admin startproject' using Django 5.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
import shutil
import sys
# from osgeo import gdal

# 從環境變數中讀取 GDAL_LIBRARY_PATH
# GDAL_LIBRARY_PATH = r'D:\Users\qwepo\anaconda3\Library\bin\gdal.dll'

## docker用須為系統變量
# os.environ['GDAL_LIBRARY_PATH'] = '/opt/conda/envs/geoDjangoMapTest/lib/libgdal.so'
# os.environ['PROJ_DATA'] = '/opt/conda/envs/geoDjangoMapTest/share/proj'


# GDAL_LIBRARY_PATH = os.getenv('GDAL_LIBRARY_PATH')

#改直接把gdal dll放到專案
from pathlib import Path
BASE_DIR = Path(__file__).resolve().parent
os.environ['GDAL_LIBRARY_PATH'] = str(BASE_DIR / 'gdal.dll')


BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
STATIC_ROOT = os.path.join(BASE_DIR, 'StaticFile')
STATIC_URL = "/static/"
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]


from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-uiiwkselvf1#z63go-bn2m25ud^s$_6(5ak#imh+#h3erofty9"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.gis",
    "world",
# 'registration',
  'leaflet',

]



REGISTRATION_OPEN = True # 设为 True，允许用户注册
ACCOUNT_ACTIVATION_DAYS = 7  # 留一周的激活时间；当然，也可以设为其他值
REGISTRATION_AUTO_LOGIN = True   # 设为 True，注册后自动登录
LOGIN_REDIRECT_URL = '/rango/'   # 登录后呈现给用户的页面
LOGIN_URL = '/accounts/login/'   # 未登录以及访问需要验证身份的页面时重定向的页面


MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "geodjango.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        'DIRS': [os.path.join(BASE_DIR, 'templates')],  # 指定全局模板目录
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "geodjango.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.contrib.gis.db.backends.postgis",
        "NAME": "catcoffee",  # 本地資料庫名稱
        "USER": "postgres",  # 通常是 postgres 作為本地資料庫的預設使用者
        "PASSWORD": "3124369",  # 你的 PostgreSQL 密碼
        "HOST": "localhost",  # 本地資料庫的主機
# 'HOST': 'postgis',
# 'HOST': 'catDB',


# 'HOST': '172.17.0.3',
        "PORT": "5432",  # PostgreSQL 預設的埠號，通常是 5432
    },
}



# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",

    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "zh-hant"  # 繁體中文

TIME_ZONE = "Asia/Taipei"  # 設置為台北時區（或根據你的時區更改）

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/



# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
LEAFLET_CONFIG = {
    'DEFAULT_CENTER': (0, 0),
    'DEFAULT_ZOOM': 3,
    'MIN_ZOOM': 3,
    'MAX_ZOOM': 18,
    'SCALE': 'both',

}
CSRF_TRUSTED_ORIGINS = [
    'https://localhost',
    'https://127.0.0.1',
    'http://127.0.0.1',
    'http://localhost',
    'https://192.168.3.20',
    'https://192.168.3.6',
    'https://geodjango.luckyciou.com',

]
ALLOWED_HOSTS = ['*']