# Generated by Django 5.1.4 on 2025-03-17 02:04

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("owner", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="catCoffee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("address", models.CharField(max_length=50)),
                ("type", models.CharField(max_length=50)),
                ("price", models.PositiveIntegerField()),
                ("comments", models.CharField(max_length=100)),
                ("location", django.contrib.gis.db.models.fields.PointField(srid=3826)),
            ],
            options={
                "verbose_name_plural": "catCoffee",
            },
        ),
    ]
