# Generated by Django 5.1.4 on 2025-03-17 03:16

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("world", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="kaohsiung",
            fields=[
                ("gid", models.AutoField(primary_key=True, serialize=False)),
                ("townid", models.CharField(blank=True, max_length=8, null=True)),
                ("towncode", models.CharField(blank=True, max_length=12, null=True)),
                ("countyname", models.CharField(blank=True, max_length=12, null=True)),
                ("townname", models.CharField(blank=True, max_length=12, null=True)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.GeometryField(
                        blank=True, null=True, srid=4326
                    ),
                ),
            ],
            options={
                "db_table": "kaohsiung",
            },
        ),
    ]
