# Generated by Django 5.1.4 on 2025-03-17 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("world", "0002_kaohsiung"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="kaohsiung",
            options={"managed": False},
        ),
    ]
