# Generated by Django 5.1.4 on 2025-03-17 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("world", "0003_alter_kaohsiung_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="kaohsiung",
            options={},
        ),
    ]
