# Generated by Django 5.1.4 on 2025-04-15 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("world", "0004_alter_kaohsiung_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="catcoffee",
            old_name="price",
            new_name="rate",
        ),
    ]
